kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: userguide-test-wc1102-admin
  namespace: userguide-test-wc1102
subjects:
  - kind: Group
    name: "github:webops"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: userguide-test-wc1102
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller
  namespace: userguide-test-wc1102
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: userguide-test-wc1102
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io